[package]
name = "cimvr_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cimvr_engine = { path = "../engine" }
cimvr_common = { path = "../common" }

bytemuck = "1.12.1"
glutin = "0.29.1"
nalgebra = { version = "0.31.4" }
glow = "0.11.2"
