[workspace]
members = [
    "engine_interface",
    "engine",
    "common",
    "server",
    "plugin",
    "plugin2",
    "plugin3",
]
# Causes a build issue with OpenXR if included in workspace
exclude = [
    "client",
]

[profile.release]
#debug = true
