[workspace]
members = [
    "engine_interface",
    "engine",
    "common",
    "server",
    "example_plugins/arcball_camera",
    "example_plugins/channels",
    "example_plugins/dancing_cubes",
    "example_plugins/cube",
    "example_plugins/ecs",
    "example_plugins/hello",
    "example_plugins/ui_example",
]
# Causes a build issue with OpenXR if included in workspace
exclude = [
    "client",
]

[profile.release]
#debug = true
