[workspace]
members = [
    "engine_interface",
    "engine",
    "common",
    "server",
    "plugin",
    "plugin2",
    "plugin3",
    "example_plugins/channels",
    "example_plugins/hello",
    "example_plugins/ecs",
]
# Causes a build issue with OpenXR if included in workspace
exclude = [
    "client",
]

[profile.release]
#debug = true
