[package]
name = "cimvr_engine_interface"
version = "0.1.0"
edition = "2021"

[features]
serverside = []

[dependencies]
bincode = "1.3.3"
serde = { version = "1", features = ["derive"] }
once_cell = "1.16.0"
log = "0.4.17"
