[package]
name = "particle-life-2d"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cimvr_common = { path = "../../common" }
cimvr_engine_interface = { path = "../../engine_interface" }
serde = { version = "1", features = ["derive"] }
zwohash = "0.1.2"
