[package]
name = "cimvr_common"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.31.4", features = ["serde-serialize"] }
cimvr_engine_interface = { path = "../engine_interface" }
serde = { version = "1", features = ["derive"] }
bytemuck = "1.12.3"
